### ISSUE TITLE
Your Address and Your Details are being swapped in checkout view

### ISSUE THREAD

**Issue by jurajdurajka** [firesale/firesale#321]
FireSale v1.2.1 (base, without any additional modules)

While in Checkout, under Shipping Details (or Billing Details), the address form contains two columns: Your Address and Your Details. If a user has e.g. one address already saved, and clicks on "Create new address" radio, these columns get swapped.

This is probably because they are selected in firesale.css file through 

``` css
.firesale#checkout fieldset > ul:nth-child(odd) { float: left; }
.firesale#checkout fieldset > ul:nth-child(even) { float: right; }
```

and the "even" and "odd" changes with the number of user's already saved addresses.
